@URL=http://localhost:5000/api

###
### get all students
###
GET {{URL}}/students/

###
### add student
###
POST {{URL}}/students/
Content-Type: application/json

{
    "prn":"22311908",
    "name":"Rashmi Apte",
    "department":"Computer Science",
    "university":"SPPU",
    "email":"rashmiapte1@gmail.com",
    "phone":"9523532366",
    "photo":"https://robohash.org/8ebacdfb1779b6c51989bfb08659a7b1?set=set4&bgset=&size=400x400"
}

###
### update student record 
###
PUT {{URL}}/students/21910718
Content-Type: application/json

{
    "prn": "21910718",
    "name": "prerna",
    "department": "cs",
    "university":"SPPU",
    "email": "prernaphadnis6@gmail.com",
    "phone": "9176565672",
    "photo":"https://robohash.org/8ebacdfb1779b6c51989bfb08659a7b1?set=set4&bgset=&size=100x100"
}

###
### get a student by prn
###
GET {{URL}}/students/21910718

###
### delete a student by prn
###
DELETE {{URL}}/students/27468854

###
### generate id card
###
GET {{URL}}/students/21910718/id-card
